"""Editable Prague itinerary. Times are departure times; transfers use a range.
Numeric timings drive both the rendered page and the arithmetic checks.
"""
UPDATED = '23 September 2026'
BASE = 'Haštalské náměstí, Prague'

SOURCES = {
 'castle': ('Prague Castle: winter hours', 'https://www.hrad.cz/en/prague-castle-for-visitors/opening-hours'),
 'castle-tickets': ('Prague Castle: official tickets', 'https://www.hrad.cz/en/prague-castle-for-visitors/tickets'),
 'lobkowicz': ('Lobkowicz Palace: hours and tickets', 'https://www.lobkowicz.cz/en/lobkowicz-palace'),
 'jewish': ('Jewish Museum: 2026 opening hours', 'https://www.jewishmuseum.cz/en/info/visit/opening-hours/'),
 'jewish-tickets': ('Jewish Museum: admission and circuit', 'https://www.jewishmuseum.cz/en/info/visit/admission/'),
 'hall': ('Old Town Hall: hours and tours', 'https://prague.eu/en/objevujte/old-town-hall-with-astronomical-clock-staromestska-radnice-s-orlojem/'),
 'municipal': ('Municipal House: English tours', 'https://www.obecnidum.cz/en/tours/'),
 'troja': ('Troja: Czech opening-hours page', 'https://www.botanicka.cz/pro-navstevniky/zakladni-informace/oteviraci-doba.html'),
 'troja-access': ('Troja: access and greenhouse information', 'https://www.botanicka.cz/en/for-visitors/basic-info/faq-the-most-frequently-asked-questions'),
 'crystal': ('Crystal Garden: 2026 programme', 'https://www.botanicka.cz/en/articles/events/what-s-on-this-year'),
 'university': ('Charles University garden: official visitor information', 'https://natur.cuni.cz/bz-uk/navstivte-nas'),
 'petrin': ('Petřín Tower: opening hours', 'https://prague.eu/en/objevujte/petrin-tower-petrinska-rozhledna/'),
 'funicular': ('PID: Petřín funicular', 'https://pid.cz/en/funicular/'),
 'nicholas': ('St Nicholas, Lesser Town: hours', 'https://prague.eu/en/objevujte/st-nicholas-church-at-mala-strana-kostel-sv-mikulase-mala-strana/'),
 'waldstein': ('Waldstein Garden: seasonal access', 'https://prague.eu/en/objevujte/wallenstein-garden-valdstejnska-zahrada/'),
 'markets': ('Prague City Tourism: 2026 market calendar', 'https://prague.eu/en/akce-kategorie/markets/'),
 'mira': ('Náměstí Míru: market dates', 'https://prague.eu/en/objevujte/namesti-miru-peace-square/'),
 'republiky': ('Náměstí Republiky: market dates', 'https://prague.eu/en/objevujte/namesti-republiky-square/'),
 'fares': ('PID: 2026 fares', 'https://pid.cz/en/tickets-and-fare/'),
 'pid': ('PID journey planner', 'https://pid.cz/en/'),
 'smartwings': ('Smartwings: check-in rules', 'https://www.smartwings.com/en/at-the-airport-on-board/'),
 'airport': ('Prague Airport: recommended arrival time', 'https://www.prg.aero/en/odbavte-se'),
 'terminal': ('Prague Airport: Tel Aviv uses Terminal 1', 'https://www.prg.aero/en/tel-aviv-jaffa'),
 'agnes': ('Residence Agnes: rooms and location', 'https://www.residenceagnes.com/standard-room'),
 'josef': ('Hotel Josef: room categories', 'https://www.hoteljosef.com/rooms-overview/'),
 'hastal': ('Hotel Haštal: official website', 'https://www.hastal.com/en/'),
 'books': ('Shakespeare and Sons: address and hours', 'https://prague.eu/en/objevujte/shakespeare-and-sons/'),
 'palladium': ('Palladium: shops and current hours', 'https://www.palladiumpraha.cz/en/shops-services/'),
 'quadrio': ('Quadrio: shops and Kafka sculpture', 'https://prague.eu/en/objevujte/quadrio/'),
 'strahov': ('Strahov Library: visit and access limits', 'https://www.strahovskyklaster.cz/en/for-visitors'),
 'clementinum': ('Clementinum: ticket release and tour access', 'https://prague.eu/en/objevujte/the-clementinum-astronomical-tower-and-baroque-library/'),
 'bolt': ('Bolt: example Prague journey estimate', 'https://bolt.eu/en-cz/cities/prague/route/praha-hlavni-nadrazi-to-andel/'),
}

def row(time, name, kind, mode, low, high, visit, text='', note='', source=None,
        target=None, slot=None, buffer=0, close=None, cover=(), opening=None):
    return dict(time=time, name=name, kind=kind, mode=mode, low=low, high=high,
                visit=visit, text=text, note=note, source=source, target=target or name+', Prague',
                slot=slot, buffer=buffer, close=close, cover=list(cover), opening=opening)

DAYS = [
 dict(id='d1', date='2026-12-18', label='Fri · 18 Dec', title='Flight to Prague; settle in',
      load='Arrival evening', intro='Smartwings flight option supplied by you; assumed, not booked. All flight times are local.',
      rows=[
       row('18:25','TLV → PRG','flight','flight',250,250,0,
           'Depart Ben Gurion at 18:25 Israel time; arrive Prague at 21:35 Czech time. Elapsed flight time: 4 hours 10 minutes.',
           'The clocks differ by one hour in December. Quoted fare: US$343 each, US$686 for two, supplied by you and not re-priced. Check baggage, seats, seller and cancellation conditions before payment.',target='Václav Havel Airport Prague Terminal 1'),
       row('21:35','Prague Airport Terminal 1','airport','passport control + baggage',45,90,0,
           'Allow for disembarkation, entry formalities and checked bags. This is a planning range, not a promise of when you will be outside.',source='terminal'),
       row('~22:30','Hotel in the Haštalská area','hotel','Bolt / Uber + collection',40,65,20,
           'Order after collecting the bags. Aim for the hotel around 23:10–23:40; a slow arrival can push this later.',
           'Confirm a staffed late check-in or working self-check-in instructions. Eat before flying or arrange a late snack; do not depend on a restaurant kitchen remaining open.',target=BASE),
      ], dinner='A snack at or near the hotel if needed. No sightseeing planned on arrival.',
      notes=[('Flight assumption','No flight numbers, reservations or baggage allowances have been inferred. Select the fare only after checking the final airline or seller terms.')]),

 dict(id='d2', date='2026-12-19', label='Sat · 19 Dec', title='Hradčany, the Castle and Lobkowicz',
      load='Moderate · tram uphill; walk within the Castle',
      intro='Breakfast at leisure; leave the hotel at 10:00. Approach from the west, then work east through the Castle.',
      rows=[
       row('10:00','Hradčanské náměstí','historic square / Hradčany district','walk + tram + walk',35,50,25,
           'From Haštalská, walk to Dlouhá třída; tram towards Malostranská, change to tram 22 towards Pohořelec. Walk downhill through the Hradčany streets to the square and Castle entrance.',
           'About 5–8 min to the tram, 20–30 min for rides and waits, then 8–12 min to the square. Confirm the December route in PID. If disrupted, Bolt to the legal Hradčanské náměstí approach is the fallback, about 25–40 min including collection.',source='pid',cover=('hradcany',)),
       row('11:15','St Vitus Cathedral','cathedral interior','walk + admission allowance',10,15,60,
           'Enter the Prague Castle complex and visit the full ticketed cathedral circuit.',
           'Buy the Castle circuit ticket once. Cathedral service restrictions override the normal Saturday 09:00–16:00 visitor hours.',source='castle',close='16:00',cover=('castle','vitus')),
       row('12:30','Old Royal Palace','palace interior','walk',3,5,35,
           'Vladislav Hall and the historic palace rooms on the Castle circuit.',source='castle',close='16:00'),
       row('13:10','Lunch near Jiřské náměstí','meal','walk',3,5,55,
           'Stay within or immediately beside the Castle complex; use the full break for lunch.',target='Jiřské náměstí Prague'),
       row('14:10','St George’s Basilica','basilica interior','walk',3,5,25,
           'The Romanesque interior on the Castle circuit.',source='castle',close='16:00'),
       row('14:40','Golden Lane','historic lane / interiors','walk',3,5,40,
           'The small houses and displays; finish before the Castle buildings close.',source='castle',close='16:00'),
       row('15:30','Lobkowicz Palace','palace museum','walk',5,10,90,
           'Audio-guided family history, paintings and musical manuscripts. A separate ticket from the Castle circuit.',
           'The published daily closing time is 18:00. This block ends about 17:10, with useful margin.',source='lobkowicz',close='18:00',cover=('lobkowicz',)),
       row('17:15','Old Town Square Christmas Market','Christmas market','downhill walk + tram + walk',30,45,105,
           'Descend the Old Castle Stairs towards Malostranská, take a suitable tram towards the Old Town, then walk to Staroměstské náměstí. Enjoy the tree, stalls and lit façades until about 19:45.',
           'If the stairs are slippery, use Bolt from a legal road pickup or return to the Castle tram stop. Road pickup is not at the palace door.',source='markets',cover=('old-market',)),
      ], dinner='Evening: dinner in Old Town; walk roughly 5–10 min from the market to a nearby restaurant, then 5–15 min to the Haštalská base.',
      notes=[('Why Saturday','The Jewish Museum is closed on Saturdays. St Vitus normally opens to tourists only at noon on Sundays, so the Castle is better here.'),
             ('If running late','Protect the cathedral, Castle closing time and Lobkowicz. Shorten the square and smaller circuit rooms before cutting lunch. A serious delay means choosing fewer Castle interiors, not arriving at closed doors.')]),

 dict(id='d3', date='2026-12-20', label='Sun · 20 Dec', title='Two botanical gardens and a local Christmas market',
      load='Higher · one cross-city car journey',
      intro='A plant-focused day. The two gardens are in different districts; a selective Bolt leg preserves the winter visiting window and keeps Monday free for shopping.',
      rows=[
       row('10:00','Charles University Botanical Garden','botanical garden / greenhouse','walk + tram + walk',30,40,60,
           'Walk about 12–15 min to Staroměstská, then take tram 18 towards Botanická zahrada and walk to the entrance on Na Slupi. Visit the greenhouse and a compact outdoor circuit.',
           'Ordinary winter greenhouse hours: 10:00–15:00; grounds: 10:00–18:00. Allow an hour here; this is the smaller of the two gardens.',source='university',close='15:00',cover=('university-garden',)),
       row('11:40','Lunch around Na Slupi / Albertov','meal','walk',5,10,45,
           'An early lunch makes the afternoon greenhouse comfortable. Choose somewhere close to the garden rather than returning to Old Town.',target='Na Slupi Prague'),
       row('12:35','Fata Morgana, Prague Botanical Garden','tropical greenhouse','Bolt / Uber including collection + short walk',35,50,80,
           'Use the Fata Morgana entrance, Trojská 750/194, rather than a generic garden pin. The greenhouse is the strongest December attraction.',
           'Tuesday–Sunday, 09:00–16:00 in winter; closed Monday. Public transport via metro C to Nádraží Holešovice and the current Troja bus is approximately 55–70 min from this area. If taking it, leave lunch earlier or shorten the outdoor loop.',source='troja',close='16:00',cover=('troja','fata'),target='Fata Morgana Trojská 750/194 Prague'),
       row('14:45','Troja outdoor collections','botanical garden / vineyard viewpoint','walk between garden sections',10,15,60,
           'Follow the signed paths towards the Japanese Garden, ornamental garden and St Claire’s Vineyard viewpoint. Individual features are within this one walking circuit.',
           'Allow the full hour for walking and looking. Outdoor planting is seasonal; use open, maintained paths. Finish the ordinary garden visit by 16:00.',source='troja',close='16:00',target='Botanická zahrada Praha Kovárna'),
       row('16:00','Náměstí Míru Christmas Market','Christmas market','walk + bus + metro + walk',45,60,75,
           'Exit towards Kovárna, take the current bus to Nádraží Holešovice, metro C to Muzeum, then metro A one stop to Náměstí Míru. The allowance includes waits and the interchange.',
           'St Ludmila’s Church is the exterior backdrop. This is the neighbourhood-market counterpoint to Old Town Square. Recheck bus routing nearer departure.',source='mira',cover=('mira-market',)),
       row('18:15','Vinohrady café break','café / neighbourhood','walk',3,5,45,
           'A warm drink and an unhurried sit-down near Náměstí Míru; the day stays active until approximately 19:05 without extending garden time past closing.',target='Náměstí Míru Prague'),
      ], dinner='Evening: dinner in Vinohrady, roughly 5–10 min on foot; return to the hotel by metro and walk in about 30–40 min, or Bolt in about 20–35 min including collection.',
      notes=[('Crystal Garden option','The exhibition is announced for 27 November 2026–14 February 2027. Its exact evening admission on 20 December has not been confirmed. If offered, it can replace the Náměstí Míru evening: book the appropriate session and visit that market on Monday after shopping. Do not assume the greenhouse stays open with the light exhibition.'),
             ('Winter hours','Troja’s English page currently disagrees with the Czech page about outdoor winter hours. This plan uses the conservative 16:00 closing confirmed by the Czech table and FAQ. No evening access is required for the main route.')]),

 dict(id='d4', date='2026-12-21', label='Mon · 21 Dec', title='A proper shopping day, with Kafka along the way',
      load='Low · a continuous central route',
      intro='No museum bookings today. The times are loose shopping blocks: spend longer wherever you find things you actually like.',
      rows=[
       row('10:00','Kafka’s rotating head at Quadrio','public sculpture','walk + metro B + walk',20,30,15,
           'Walk to Náměstí Republiky, take metro B to Národní třída, then walk to the sculpture in the Quadrio courtyard.',
           'This is David Černý’s rotating head. The different Kafka Memorial beside the Spanish Synagogue is on Tuesday. Movement is not guaranteed at every moment; no need to wait a full cycle.',source='quadrio',cover=('kafka-head',)),
       row('10:45','Quadrio','shopping centre','walk',1,3,40,
           'Browse the shops that interest you. Keep the remainder of the day for the broader choice on Wenceslas Square, Na Příkopě and Palladium.',source='quadrio'),
       row('11:30','Wenceslas Square shops','shopping boulevard / bookshops','walk',10,15,90,
           'Browse the boulevard and bookshops, including Luxor if desired. Shop visits and the short walks between them are included in this block.',target='Václavské náměstí Prague'),
       row('13:15','Lunch near Wenceslas Square','meal','walk',3,5,60,
           'A full hour for lunch, with no timed attraction immediately afterwards.',target='Václavské náměstí Prague'),
       row('14:20','Na Příkopě','shopping street','walk',5,10,90,
           'Continue north-east through the shops towards Náměstí Republiky. This is the mainstream-shopping route; Pařížská is an optional luxury-shopping substitution.',target='Na Příkopě Prague'),
       row('16:00','Palladium','shopping centre','walk',5,10,150,
           'The broadest single indoor shopping stop on the route. Stay until about 18:40, including a coffee break if wanted.',
           'Current regular shop hours extend to 21:00; specific December shop hours still need checking. No advance booking.',source='palladium',close='21:00'),
       row('18:40','Palladium café / final browsing','café / shops','walk within centre',0,5,40,
           'Finish shopping, sit down for a coffee, or bring dinner forward. This block is flexible rather than an extra attraction.',source='palladium'),
      ], dinner='Evening: dinner around Náměstí Republiky or Haštalská, about 5–10 min on foot. Walk back to the hotel in another 5–10 min.',
      notes=[('Full shopping day','Both botanical gardens are on Sunday. Monday has no garden or museum taking a chunk out of the day.'),
             ('If choosing Crystal Garden','Move Náměstí Míru market here: leave Palladium around 17:15, allow 30–40 min by metro and walking, then enjoy the market until about 19:15. This trades the last shopping block for the market.')]),

 dict(id='d5', date='2026-12-22', label='Tue · 22 Dec', title='Josefov, Old Town and the Municipal House',
      load='Low · compact, mostly level walking',
      intro='The Jewish quarter first, then a south-east progression through Old Town. Both English-tour times below are provisional until the December programmes are available.',
      rows=[
       row('10:00','Maisel Synagogue','synagogue / museum','walk',8,12,30,
           'Start the Jewish Town circuit here after breakfast. Collect or show the combined ticket.',source='jewish-tickets',close='16:30',cover=('jewish',)),
       row('10:45','Pinkas Synagogue','synagogue / memorial','walk',4,6,35,
           'Allow time for the memorial and exhibitions without treating this as a photo stop.',source='jewish',close='16:30'),
       row('11:30','Old Jewish Cemetery','historic cemetery','walk / site transition',2,5,35,
           'Continue through the cemetery route.',source='jewish',close='16:30'),
       row('12:10','Old-New Synagogue','historic synagogue interior','walk',3,5,25,
           'Select a ticket that explicitly includes the Old-New Synagogue; check the product when buying.',source='jewish-tickets',close='16:30'),
       row('12:45','Spanish Synagogue','synagogue / museum','walk',5,8,45,
           'The richly decorated interior and museum displays. These five sites are the planned circuit; extra venues are not silently added to the same time allowance.',source='jewish',close='16:30',cover=('spanish',)),
       row('13:40','Franz Kafka Memorial','public sculpture','walk',1,2,8,
           'Jaroslav Róna’s sculpture beside the synagogue, an easy stop on the way to lunch.',cover=('kafka-memorial',),target='Franz Kafka Monument Dušní Prague'),
       row('13:50','Lunch in Josefov','meal','walk',3,5,55,
           'Lunch around Dušní or V Kolkovně before the afternoon interiors.',target='Dušní Prague'),
       row('14:50','Old Town Hall','historic interiors / tower','walk + entry allowance',10,15,85,
           'Visit the tower and the historic rooms using the available English-tour schedule. The combined block allows approximately 45 min for the interior tour and 40 min for the tower and transitions.',
           'Target an interior tour at 15:15, arriving by 15:05, then the tower. Confirm the actual offered time before buying. If unavailable, retain the tower and move the interior tour to Saturday evening, replacing part of the market block and only if a suitable tour is offered. Do not count a façade view as an interior visit.',source='hall',slot='15:15',buffer=10,close='20:00',cover=('hall',)),
       row('16:40','Old Town Square and Týn','historic square / church exterior','walk',2,3,12,
           'See Staroměstské náměstí by late afternoon and the Church of Our Lady before Týn from outside, as requested.',cover=('old-square','tyn'),target='Church of Our Lady before Týn Prague'),
       row('16:55','Astronomical Clock','clock exterior','walk',2,3,12,
           'Reach the clock around 16:57–16:58 for the 17:00 procession, then see the dial and façade. The procession is brief; do not wait another hour if a delay makes you miss it.',cover=('clock',),target='Prague Astronomical Clock'),
       row('17:15','Powder Gate and Municipal House approach','historic gate exterior / street','walk via Celetná',10,15,10,
           'Walk east along Celetná to the Powder Gate, then continue to the Municipal House entrance next door.',target='Powder Tower Prague'),
       row('17:40','Obecní dům, Municipal House','Art Nouveau interior tour','walk',2,5,60,
           'Target an 18:00 English guided tour, lasting about an hour. Arrive by 17:45 for a 15-minute check-in margin.',
           '18:00 is a requested slot, not a published departure or a booking. If the programme offers an earlier afternoon tour, swap the Old Town Hall to afterwards, subject to its last English tour. An exterior visit alone does not fulfil the planned interior.',source='municipal',slot='18:00',buffer=15,cover=('municipal',)),
       row('19:00','Náměstí Republiky Christmas Market','Christmas market','walk',2,5,30,
           'Browse the stalls next to the Municipal House. The market dates are published; the 22 December evening closing time must still be checked. If it closes earlier, use the 17:15–17:40 approach block for the stalls and shorten the gate stop.',source='republiky',cover=('republiky-market',)),
      ], dinner='Evening: dinner near Náměstí Republiky, about 5–10 min on foot; another 5–10 min walk to the Haštalská base.',
      notes=[('Booking order','Set the Municipal House English tour first, then fit the Old Town Hall tour around it. Neither provisional time is a purchased ticket.'),
             ('Circuit coverage','The Jewish Museum is a collection of sites, not an extra building after the synagogues. The core circuit is explicit above. Check any newly reopened venues before deciding whether to add more museum time.')]),

 dict(id='d6', date='2026-12-23', label='Wed · 23 Dec', title='Petřín, Lesser Town, books and Charles Bridge',
      load='Moderate · funicular uphill; walk downhill',
      intro='Choose the clearest forecast for Petřín if a day swap is possible. Today is the main Lesser Town visit, with the illuminated bridge after dark and the last flagship market afterwards.',
      rows=[
       row('10:00','Petřín Tower','viewing tower','walk + tram + funicular + walk',45,65,60,
           'Walk to Dlouhá třída, take a suitable tram towards Újezd, then the funicular uphill and walk to the tower. The allowance includes ordinary waits and up to about 15 minutes of queuing.',
           'The funicular resumed service in September 2026. A 24-hour PID ticket covers it. If the queue adds more than 20 minutes, shorten the park circuit; do not let it push St Nicholas past closing.',source='petrin',close='18:00',cover=('petrin-tower',)),
       row('12:05','Petřín Hill','park / viewpoints','walk within park',0,0,30,
           'A short circuit of the tower surroundings and available viewpoints before descending. The full half-hour includes all local walking.',cover=('petrin',),target='Petřín Gardens Prague'),
       row('12:35','Lunch at Újezd','meal','walk + funicular downhill + walk',20,30,60,
           'Walk back to the upper station and descend to Újezd. Have lunch near the lower station.',source='funicular',target='Újezd Prague'),
       row('14:05','St Nicholas Church, Malá Strana','Baroque church interior','walk gently uphill',15,20,45,
           'The major Lesser Town church on Malostranské náměstí, not the different St Nicholas church in Old Town Square.',source='nicholas',close='17:00',cover=('nicholas',)),
       row('15:10','Malostranské náměstí and Lesser Town lanes','historic district','walk within district',0,0,25,
           'Explore the square and nearby lanes towards Mostecká. All local walking is included; continue downhill.',cover=('lesser-town',),target='Malostranské náměstí Prague'),
       row('15:35','Kampa and Na Kampě','riverside park / square','walk downhill',8,12,25,
           'River views and the quiet lanes south of the bridge. Stay on clear main paths; the park is a short outdoor stop in December.',target='Na Kampě Prague'),
       row('16:15','Shakespeare and Sons','bookshop interior','walk',8,12,35,
           'Browse the English-language shelves at U Lužického semináře 10. This is a proper bookshop visit, not just the façade.',source='books',close='19:00',cover=('bookshop',)),
       row('17:05','Charles Bridge','historic bridge / riverside views','walk',3,5,35,
           'Cross from Lesser Town to Old Town after dark, with the city lights reflected on the river. The 35-minute block includes the crossing, photographs and pauses.',cover=('bridge',)),
       row('17:50','Wenceslas Square Christmas Market','Christmas market','walk via Karlova and Old Town lanes',18,22,75,
           'End at the lower part of Václavské náměstí for the second flagship market, until approximately 19:25.',source='markets',close='22:00',cover=('wenceslas-market',)),
      ], dinner='Evening: dinner near Wenceslas Square, 5–10 min on foot. Return to the hotel in about 20–25 min on foot, or 15–25 min by metro and walking; pack tonight.',
      notes=[('Bad visibility','If the tower offers no view, the optional Strahov Library is a more useful replacement: allow about 45–60 min, plus transport via Pohořelec. Standard tickets provide doorway views into the halls, not access among the books. Rejoin Lesser Town for lunch; do not add it on top of the whole morning.'),
             ('Waldstein Garden','Closed in December, so it is not promised as a visit. The same seasonal issue affects many formal Castle gardens. Petřín and Kampa supply the outdoor park time instead.')]),

 dict(id='d7', date='2026-12-24', label='Thu · 24 Dec', title='Breakfast, airport and home',
      load='Departure day · earlier airport transfer',
      intro='The 12:45 flight requires a departure before 10:00. This exception applies only to the travel day; every sightseeing day starts at 10:00.',
      rows=[
       row('08:00','Breakfast at the hotel','meal','in hotel',0,0,60,
           'A calm breakfast, with the bags already packed the night before. Confirm breakfast service on Christmas Eve.',target=BASE),
       row('09:00','Check-out and car collection','hotel','in hotel / outside entrance',0,0,15,
           'Use a pre-arranged transfer or check both ride-hailing apps in advance. Aim to have the car at the hotel by 09:15.',target=BASE),
       row('09:15','Prague Airport Terminal 1','airport','car',30,45,0,
           'Arrive around 09:45–10:00, at least 2¾ hours before the flight. Allow more if the airline sends a specific earlier reporting instruction.',
           'Prague Airport recommends at least 2½ hours. Smartwings normally opens check-in 2½ hours before departure. No sightseeing, market stop or shopping before the airport.',source='airport',slot='12:45',buffer=150,target='Václav Havel Airport Prague Terminal 1'),
       row('12:45','PRG → TLV','flight','flight',230,230,0,
           'Assumed Smartwings departure 12:45 Czech time; arrival at Ben Gurion 17:35 Israel time. Elapsed flight time: 3 hours 50 minutes.',
           'The return flight and fare remain an assumption until booked. Recheck the terminal and schedule on the airline booking.',source='smartwings',target='Ben Gurion Airport'),
      ], dinner='', notes=[('Travel-day trade-off','A strict 10:00 hotel departure would remove too much airport margin for this flight. Keeping the 12:45 flight therefore means one earlier breakfast and transfer.')]),
]

HOTELS = [
 ('Best fit: Haštalská / Haštalské náměstí',
  'Stay in north-eastern Old Town, within roughly 5–10 minutes of Old Town Square and Náměstí Republiky. The small streets near Haštalská balance walkability, breakfast convenience and access to trams. Route estimates use Haštalské náměstí as the provisional starting point.',
  'Choose a rear or courtyard-facing room. Dlouhá itself has bars and evening activity: proximity is useful, a room directly over them is not the sleep-first choice. Confirm good sound insulation, heating, blackout curtains, a lift where needed, and late arrival after 23:00.'),
 ('Alternative: quieter streets near Náměstí Republiky',
  'Convenient for shopping, the Municipal House and metro B. A hotel just off the main tram street is preferable for sleep; allow an extra 5–10 minutes on some Old Town walks.',
  'Ask which way the actual room faces. A central address alone does not establish quietness.'),
 ('Alternative: lower Malá Strana / Kampa',
  'Atmospheric for a couple and well placed for the Castle, Petřín and Charles Bridge. Stay near the lower tram corridor rather than high up Nerudova.',
  'This moves the hotel to the other bank and requires recalculating the first and last legs of every day. Old Town remains the best overall fit for this particular five-day route.'),
]

BOOKINGS = [
 ('Now, cancellable', 'Hotel, six nights: 18–24 December',
  'Reserve a free-cancellation room with breakfast only if the total rate and cancellation deadline suit you. Check whether any deposit is refundable. Room orientation and late check-in matter more here than a view of the market.', 'agnes'),
 ('Choose deliberately', 'Smartwings flights',
  'Use the supplied schedule and US$686 quotation as a working assumption only. Verify the final fare, operating airline, cabin and checked-bag allowance, seating fees and cancellation/change terms. No purchase has been made.', 'smartwings'),
 ('When trip confirmed', 'Municipal House English tour',
  'This is the main schedule-dependent reservation. Check the official programme for 22 December, aiming at 18:00; book as soon as a suitable slot appears after the trip is confirmed. An exact release date is not published. Set this before the Old Town Hall tour.', 'municipal'),
 ('When trip confirmed', 'Old Town Hall interiors and tower',
  'Choose the product including the historical interiors and tower, then fit an English tour around 15:15 on 22 December. These are target times only. Published Christmas exceptions still refer to the previous season, so use the 2026 booking calendar when available.', 'hall'),
 ('Near date', 'Castle circuit and Lobkowicz Palace',
  'Buy through the official sellers once travel is secure, typically several days before, subject to availability. Lobkowicz is separate. Recheck Cathedral services and closures; a ticket does not override them. Do not book a tour that starts before the planned arrival.', 'castle-tickets'),
 ('Near date', 'Jewish Town ticket',
  'Buy the combined product including the Spanish and Old-New synagogues. The plan visits five named sites. Check current access and terms; an online ticket does not guarantee no entry queue.', 'jewish-tickets'),
 ('Near date / on day', 'Botanical gardens and Petřín',
  'Ordinary visits do not need a months-ahead commitment. Use official tickets near the visit; keep Petřín weather-flexible. Confirm the university greenhouse’s current payment method and carry some CZK. Crystal Garden evening tickets are a separate decision once 20 December sessions and terms are published.', 'troja'),
 ('Once dates secure', 'One or two special dinners',
  'Reserve only restaurants you particularly care about, preferably without a non-refundable deposit. Keep evening dinner times flexible and fit them to the final tour or exhibition time. No named restaurants are imposed by this itinerary.', None),
 ('1–3 days before', 'Airport transfer and check-in',
  'Confirm a 09:15 pickup on 24 December and the hotel’s Christmas Eve breakfast. Arrange reliable collection rather than treating an app estimate as a guarantee. Smartwings online check-in normally opens 30 hours before departure; confirm whether your flight is eligible.', 'smartwings'),
 ('No booking', 'Markets, public transport and ordinary shopping',
  'The four listed markets need no admission reservation. Buy or activate transit tickets when needed; no car hire is useful for this route.', 'fares'),
]

MARKETS = [
 ('Old Town Square', 'Flagship: tree, setting and atmosphere', '28 Nov 2026–6 Jan 2027', 'Saturday evening', 'markets'),
 ('Wenceslas Square', 'Second flagship; convenient with New Town', '28 Nov 2026–6 Jan 2027', 'Wednesday evening; listed 10:00–22:00', 'markets'),
 ('Náměstí Míru', 'Neighbourhood feel and craft stalls', '20 Nov–24 Dec 2026', 'Sunday evening; listed 10:00–20:00', 'mira'),
 ('Náměstí Republiky', 'Compact market beside Municipal House', '25 Nov–24 Dec 2026', 'Tuesday; final evening hours to confirm', 'republiky'),
]

REQUIRED = {'old-square','castle','vitus','bridge','hall','clock','kafka-head','kafka-memorial',
            'petrin','petrin-tower','lesser-town','lobkowicz','municipal','spanish','jewish',
            'nicholas','tyn','hradcany','old-market','wenceslas-market','mira-market','republiky-market',
            'troja','fata','university-garden','bookshop'}
